### ISSUE TITLE
Investigate why resources without extension are not correctly loaded by Firefox

### ISSUE THREAD

**Issue by Gnafu** [georchestra/mapstore2-georchestra#126]
It looks like gzipped resources fail to be decoded on the fly by Firefox
Clearing the "network.http.accept-encoding.secure" config mitigates the problem but it is a client side change.
We need to provide a solution

Test different Nginx configurations

Related to https://github.com/geosolutions-it/MapStore2/issues/4606

**Comment by mbarto** [comment]
@Gnafu maybe this one is related: https://github.com/containous/traefik/issues/2826

**Comment by mbarto** [comment]
@Gnafu, I see that we do not use traefik for mapstore, but we have the security-proxy (https://github.com/georchestra/georchestra/blob/f879c98a3b535a5ce071a6327aec2f8f369856f1/security-proxy/src/main/java/org/georchestra/security/Proxy.java) in between, so it could be that the problem is in there.
The security proxy uses apache asynchttpclient 4.1.4, that maybe does not handle gzip compression well?
As an alternative: can we disable gzip compression on the tomcat (mapstore) level?

**Comment by Gnafu** [comment]
Try this: https://stackoverflow.com/questions/58303968/how-to-set-force-content-type-of-file-that-has-no-extension-in-tomcat-7-or-above
