### ISSUE TITLE
Responsive design issue

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#156]
From @catmorales 

Test "Canevas"
i tested this functionnality  on https://georchestra.geo-solutions.it/mapstore/#/

> The viewer must fit the responsive design patterns, it must be adaptive to be compatible with different kind of screen (desktop, mobiles devices) 

I zoomed on a specifical bouding box and embedded the iframe on a html page 
* navigation buttons are not responsive 
* bounding box is not used in the iframe

![image](https://user-images.githubusercontent.com/4659829/73354583-5a8dee00-4296-11ea-94c0-b72256490bba.png)

**Comment by tdipisa** [comment]
As reported by @catmorales, the geOrchestra header should be also removed for embedded maps.

**Comment by gitcontributor** [comment]
The bug related to the header for embedded maps was fixed in this PR: https://github.com/georchestra/mapstore2-georchestra/pull/159

Here are the changes that solve the problem with the header: https://github.com/georchestra/mapstore2-georchestra/pull/159/files#diff-a7479939d23d8e9e11f0671d8cb142d6

Currently, it seems that the logic of hiding header works in the right way (I embedded the iframe in the HTML page and as you can see there is no the header):
![image](https://user-images.githubusercontent.com/61145641/77190270-ffd08000-6ae9-11ea-97af-6aeb6d7b74ca.png)
cc: @tdipisa @catmorales
