### ISSUE TITLE
Maps plugins - Clarification and translation

### ISSUE THREAD

**Issue by catmorales** [georchestra/mapstore2-georchestra#209]
I am a little bit confused with all the map plugins and their denominations.
This issue is made to exchange on this subject.

In the CCTP we defined:

* **map**= layers+bounding box+base layers : 
** users maps : current or saved
** administrator maps = "cartes modèles" publics or specific to a context
* **context** = map+plugins+rights (public,...)
** user contexts : current or saved
** administrator contexts = context+name+specific url+rights (public, ...)

If i resume plugins:

1-  **Map** = "Zone de carte (CCTP 3.2.1.2)" -required plugin loaded by default 
https://mapstore.geo-solutions.it/mapstore/docs/api/plugins#plugins.Map

2- **Map templates** = "Cartes modèles (CCTP 3.2.2.6) "
They are loaded by the administrator for a defined context and are visible only in this context in the "Modèles de cartes". The user can add it to the current map or replace it. 
We can say that they are **administrator's maps** 
I didn't see the api documentation, perhaps, its not available yet

3-  **Exportation de carte** = "Gestion des cartes utilisateurs" (CCTP 3.2.2.7) --> 
Export the map in wmc or json file.
I didn't see the api documentation, perhaps, its not available yet

4-  **Sauvegarder** = Gestion des cartes utilisateurs (CCTP 3.2.2.7 and 3.2.2.8)
User can save it's map and  all the fonctionnalities too : bounding box, layers and extensions. 
In database ? 

I didn't see the api documentation, perhaps, its not available yet

5-  **Catalogue de cartes** = Gestion des cartes / contextes utilisateurs (CCTP 3.2.2.7 and 3.2.2.8)
I think that we need another word as "map" because it's more like a context here.
The user can manage its maps, other users maps, see all the public users maps and load a map.

When he load a "map" , this one replace the current map and loaded plugins.

I didn't see the api documentation, perhaps, its not available yet

 6- **Links** :
* first context : https://georchestra.geo-solutions.it/mapstore/#/context/TestCatherine_complet
* after modification of the current map of this context: https://georchestra.geo-solutions.it/mapstore/#/context/TestCatherine_complet/1743
* after saving the map by the "Sauvegarder" plugin: https://georchestra.geo-solutions.it/mapstore/#/viewer/openlayers/883
The first one is the "administrator context"
The second one is the current modify context
The last one is shared and visible on the" Catalogue de cartes"
**Is every number an id from the database where is stored the map ?**

We have to make you a proposal for the French denominations.

**Comment by catmorales** [comment]
@tdipisa  questions on the users map catalog (points4, 5 and 6 above) :

1- Tt seems that the maps saved in the user catalogs are more similar as contexts than maps. 
Do you confirm that ?
So why we don't see in this catalog the administrators public contexts ?  does it mean that there is two catalogs (administrators and users)  ? 

2- is it possible to add this plugin in the mapstore base map, in the localconfig.json, i imagine ?

**Comment by tdipisa** [comment]
>1- Map = "Zone de carte (CCTP 3.2.1.2)" -required plugin loaded by default
https://mapstore.geo-solutions.it/mapstore/docs/api/plugins#plugins.Map

Yes, this is a required plugin for all map viewers obviously.

>2- Map templates = "Cartes modèles (CCTP 3.2.2.6) "
They are loaded by the administrator for a defined context and are visible only in this context 
in the "Modèles de cartes". The user can add it to the current map or replace it.

Correct, anyway the administrator can obviously create another context by putting in it the same tempates if he wants (all uploaded templates are available in the app context wizard)

>We can say that they are administrator's maps

Yes, more or less. The administrator can define permission rules (through the wizard UI) in the same way of other resources in MapStore in order to make Map Templates (if the plugin is enabled) publicly visible or visible in the viewer UI only to certain groups of users (however only the administrator can edit MapTemplates contents from the wizard UI)
 
>I didn't see the api documentation, perhaps, its not available yet

The user guide is still in progress

>3- Exportation de carte = "Gestion des cartes utilisateurs" (CCTP 3.2.2.7) -->
Export the map in wmc or json file.

Yes, the Map Import/Export is only a part of this requirement: "Gestion des cartes utilisateurs" (CCTP 3.2.2.7)

>I didn't see the api documentation, perhaps, its not available yet

The user guide is still in progress, a draft is available here:
https://mapstore.readthedocs.io/en/userguide_updating2/user-guide/import/

>4- Sauvegarder = Gestion des cartes utilisateurs (CCTP 3.2.2.7 and 3.2.2.8)
User can save it's map and all the fonctionnalities too : bounding box, layers and extensions.
In database ?

Yes, in MapStore the persistance is in the DB.
Please, take into account that requirement 3.2.2.8 is still in progress, we made some relevant progress but it isn't complete yet (probably in a couple of days)

>I didn't see the api documentation, perhaps, its not available yet

The user guide is still in progress for what concerns the User Map Catalog (CCTP 3.2.2.7), for 
the User Session (CCTP 3.2.2.8) we will start documenting it as soon as we finish the implementation.

>5- Catalogue de cartes = Gestion des cartes / contextes utilisateurs (CCTP 3.2.2.7 and 3.2.2.8)
I think that we need another word as "map" because it's more like a context here.
The user can manage its maps, other users maps, see all the public users maps and load a map.

This tool allows the user to manage all of his maps, created across different contexts. In the list 
can be also present maps created by other users that have decided to set them as public (a map is private by default in MapStore)

>When he load a "map" , this one replace the current map and loaded plugins.

Of course, when the user saves a map within a context he create a context map that is based on the context and therefore uses the same set of plugins of the starting context.

>I didn't see the api documentation, perhaps, its not available yet

The user guide is still in progress for this.

>6- Links :

>first context : https://georchestra.geo-solutions.it/mapstore/#/context/TestCatherine_complet
after modification of the current map of this context: https://georchestra.geo-solutions.it/mapstore/#/context/TestCatherine_complet/1743
after saving the map by the "Sauvegarder" plugin: https://georchestra.geo-solutions.it/mapstore/#/viewer/openlayers/883
The first one is the "administrator context"
The second one is the current modify context
The last one is shared and visible on the" Catalogue de cartes"

The third URL you mentioned isn't correct, we made some fixes recently. 
For this reason, starting from the last deploy we made, I would like to kindly ask you to test these things by creating new contexts from scratch, just to be sure that all things you test are correclty aligned with latest updates.

>Is every number an id from the database where is stored the map ?

Yes, if you save a map starting from a context, you create your own **context map**: the viewer of this map uses the same set of plugins of the original context with your custom contents if they have been included.

>@tdipisa questions on the users map catalog (points 4, 5 and 6 above) :

>1- It seems that the maps saved in the users catalog are more similar as contexts than maps.
Do you confirm that ?

I've explained this above, anyway:

A context is a viewer configuration (with a specific URL associated, wizard step 1) where the administrator can configure the plugins to include and he can configure map contents. Therefore users that can access to the context, can work in a **context specific** viewer with the desired set of plugins configured by the administrator. At this point, if the **Save plugin** has been enabled by the administrator for that context, the user can also save a **context map** by including his modifications too: a context map has the same viewer (set of plugins) of the context with custom modifications made by the user (on catalog sources, layers, background layers, TOC etc.)

>So why we don't see in this catalog the administrators public contexts ? does it mean that there is two catalogs (administrators and users) ?

Application Contexts can be created and managed only by the administrator that can create them and share them publicly or only to specific groups of users.

![image](https://user-images.githubusercontent.com/1280027/78135417-282d7800-7422-11ea-8a5e-085683597a8b.png)

An user can access the context and, if allowed, save his custom context maps.

>2- Is it possible to add this plugin in the mapstore base map, in the localConfig.json, i imagine ?

Yes, it is possible.

**Comment by catmorales** [comment]
ok thank you tobia !

**Comment by catmorales** [comment]
So, i will initialize all my application contexts

**Comment by tdipisa** [comment]
@catmorales yes, ok.

**Comment by catmorales** [comment]
Currently,  we offers on mapfishapp, the possibilities for all  users , to add map templates (prepared by the administrator)  in the standard viewer. So i suppose that it can be possible to reproduce  it , adding the map templates plugin in the localConfig.json.
@tdipisa Isn't it ?

**Comment by catmorales** [comment]
Another question , i don't remember if we spoke about it before.

* https://georchestra.geo-solutions.it/mapstore/#/ sent the user directly on mapstore standard map context which is configured with localConfig.json . 
It is the same bahaviour as the actual viewer of geOrchestra.

* https://georchestra.geo-solutions.it/mapstore/#/  sent the user on a map catalog where he can choose an application  context between a choice of  application contexts he can use. 
This is very convenient, i think.

What is the final product for geOrchestra ?

**Comment by tdipisa** [comment]
@catmorales 

>https://georchestra.geo-solutions.it/mapstore/#/ sent the user directly on mapstore standard application context which is configured with localConfig.json .
It is the same behaviour as the actual viewer of geOrchestra.

Yes.

>https://mapstore.geo-solutions.it/mapstore/#/ sent the user on an application contexts catalog where he can choose an application context between a choice of application contexts he can use. 

Yes, it is how the standard MapStore works but the geOrchestra environment is more viewer oriented: in the current geOrchestra the user can manage his maps directly inside the viewer and since there aren't specific requirements involving a map catalog entry page (I mean MapStore like) for geOrchestra, we haven't changed this and therefore we have maintained the same behavior. 

>This is very convenient, i think.

It could be, but it is not expected by the geOrchestra initial requirements. I have presented many times how MapStore works and the solutions that we planned to adopt in geOrchestra since the first meeting we had, but I have never received comments from you regarding this aspect: it is quite strange for me to discuss this now :) at this stage honestly I don't think we have time available to do changes regarding this, maybe in next commitments.

>What is the final product for geOrchestra ?

Considering what I wrote you above, the final product is pretty much what you are seeing now.

**Comment by landryb** [comment]
> > This is very convenient, i think.
> 
> It could be, but it is not expected by the geOrchestra initial requirements. I have presented many times how MapStore works and the solutions that we planned to adopt in geOrchestra since the first meeting we had, but I have never received comments from you regarding this aspect: it is quite strange for me to discuss this now :) at this stage honestly I don't think we have time available to do changes regarding this, maybe in next commitments.
> 
> > What is the final product for geOrchestra ?
> 
> Considering what I wrote you above, the final product is pretty much what you are seeing now.

i have to agree with @tdipisa here, the 'mapstore catalog default landing page' was known beforehand (i mean we looked at the demos before doing the requirements) and the mapstore/georchestra integration requirements didnt list it (to keep the same 'user workflow' as we had with mfapp, where users are pointed at contexts from various external locations, be it a cms, a geonetwork map metadata, etc..), it's *really* too late to change requirements at this point. Choices have been made and we stick to it :)

**Comment by catmorales** [comment]
@tdipisa and @landryb  that's OK.  
I agree with you on this point : it's not on the initial requirements and we will not change nothing.
Sorry for the noise.
