### ISSUE TITLE
Problem with printing function

### ISSUE THREAD

**Issue by jusabatier** [georchestra/mapstore2-georchestra#243]
I try to print a layer for testing this function and I've some problems : 

- When opening the printing popup, it's not centered and a part of the window is out of the screen : 

![Capture d’écran de 2020-06-08 15-41-50](https://user-images.githubusercontent.com/8310116/84037382-d0ba0400-a99e-11ea-925a-ea2626787d81.png)

- When trying to print, have an error message : 

> Error on printing: undefined

When looking in the console on web browser, it seems to have a problem with requests : 

![Capture d’écran de 2020-06-08 15-46-18](https://user-images.githubusercontent.com/8310116/84038511-55595200-a9a0-11ea-89c4-eb8a9c48c7be.png)

I checked all the configs files in mapstore datadir, and I always use https, so don't understand why it try to query the proxy with http (reason of the mixed-content error).

**Comment by jusabatier** [comment]
I notice that the first try to load create.json is : 
http://opendata.agglo-lepuyenvelay.fr/mapstore/pdf/create.json

But is blocked due to mixed-content.
I notice the same problem on https://georchestra.geo-solutions.it/mapstore/#/
This call should use https instead of http.

**Comment by MaelREBOUX** [comment]
Here I get this error 

![capture_268](https://user-images.githubusercontent.com/6370443/86576407-fd9b1000-bf78-11ea-9e5a-c29af2ba657c.png)

In the console I get 2 3002 and a 403 :

https://portail-test.sig.rennesmetropole.fr/mapstore/proxy/?url=http%3A%2F%2Fportail-test.sig.rennesmetropole.fr%2Fmapstore%2Fpdf%2Fcreate.json
302

https://portail-test.sig.rennesmetropole.fr/mapstore/proxy/?url=https%3A%2F%2Fportail-test.sig.rennesmetropole.fr%2Fmapstore%2Fpdf%2Fcreate.json
302

https://portail-test.sig.rennesmetropole.fr/mapstore/proxy/?url=https%3A%2F%2Fportail-test.sig.rennesmetropole.fr%2Fcas%2Flogin%3Fservice%3Dhttps%253A%252F%252Fportail-test.sig.rennesmetropole.fr%252Flogin%252Fcas
403

Don't understand why I'm redirected to the CAS. A problem of routing in the SP @catmorales  ?

**Comment by jusabatier** [comment]
This mornig, I upgraded our MapStore to master version.

Now the print function disapeared from maps. Ichecked that it is activated for the context and it is, but I have no button to print on the generated map.

**Comment by offtherailz** [comment]
I did[ this PR](https://github.com/georchestra/mapstore2-georchestra/pull/262) to fix the configuration, that was missing of a needed line to work with latest changes on print plugin inclusion policies.

Right now i don't merge it [because of some problems on npm](https://status.npmjs.org/) on npm the travis build will fail, but npm stuff is going to solve.As well as becomes green again, we can merge the PR.

Anyway if you look at "files" section, if you need this fix, you can apply to your localConfig.json the change while waiting for it.

**Comment by jusabatier** [comment]
Update my localConfig.json make the print function appear again, but I still can't print because of the previous error : 

![image](https://user-images.githubusercontent.com/8310116/91027856-e71a4800-e5fc-11ea-8248-9cfd5c701c89.png)

**Comment by offtherailz** [comment]
This is true in general with all the proxied services that need to forward protocol. Also GeoServer maybe affected to this kind of issues, returning http URLs instead of HTTPS
Also using AJP helps to solve the issue.

**Comment by landryb** [comment]
> I found a solution to this problem !
> 
> Our Mapstore VM is behind a Reverse Proxy, so the RP is requested over https and forward to Sec Proxy and Mapstore over http (8080).
> 
> The solution is to add in the Nginx location's config the line :
> 
> > proxy_set_header X-Forwarded-Proto https;
> 
> So tomcat's apps can make their redirects in https.
> After doing that, the printing function works well.

Well, faced the same problem, added that config line to my nginx vhost (in the one just facing tomcat), reloaded nginx, and i still see mapstore trying POST on http:// urls, which is blocked by the browser itself as it doesnt want to POST to http:// from an https page. Symptom is 'Error on printing: undefined' in the print window; right ?

**Comment by landryb** [comment]
somehow in `mapstore/pdf/info.json` return value, the urls for printURL and createURL are still over http://, even after a webapp reload.

Using tcpdump -A on the tomcat port, i see that `x-forwarded-proto: https` is set in the headers sent to tomcat. So is there something else to fiddle with, maybe in tomcat's context.xml (eg a bit like this kind of horrors: https://github.com/georchestra/georchestra/pull/3144#issue-486625322)

**Comment by landryb** [comment]
Bah; probably added it at the wrong spot, and i wonder if it doesnt conflict with proxyPort/proxyHost in the tomcat connector.. This definitely needs proper documenting, as https://github.com/georchestra/mapstore2-georchestra/issues/243#issuecomment-692110115 is not what i'd call "proper documentation" :)

**Comment by landryb** [comment]
Yeah, definitely conflict with proxyName/proxyPort. If set to port 80, and scheme isnt set, then the url built for printURL is http. Setting scheme=https + proxyport=443 in server.xml helps.

**Comment by sigrmed** [comment]
I think that we have the same problem:
![image](https://user-images.githubusercontent.com/60706935/93793075-a252f280-fc36-11ea-89e1-6cb0881211b5.png)
Catherine

**Comment by offtherailz** [comment]
I added some documentation about how to solve these kind of problems, here: 
https://mapstore.readthedocs.io/en/latest/developer-guide/printing-module/

Maybe we could link this documentation in the geOrchestra one. Anyway, a good solution could be to fix the URL to the relative one, as explained [here](https://mapstore.readthedocs.io/en/latest/developer-guide/printing-module/#forcing-print_base_url-of-printing-module) by default for MapStore inside georchestra, setting that JAVA_OPT as default. This may solve http/https issues once for all, without need to troubleshooting on any installation.

**Comment by catmorales** [comment]
>The printing module is required by the Print plugin of MapStore, so if you want to have the Print plugin working in your application, you have to include also the printing module in your MapStore installation.

Is the back printing module included in the docker image latest [here ](https://hub.docker.com/r/geosolutionsit/mapstore2-georchestra/tags) ?

In any case, it is necessary to explain or/and link  this in the mapstore2 documentation for geOrchestra because it is not really intuitive. 
I don't know how to solve it in our case, so i need expertise from  @pmauduit

**Comment by pmauduit** [comment]
> I don't know how to solve it in our case, so i need expertise from @pmauduit

Dissecting the webapp in the docker image, it seems that there is a mfprint jar customized by geosolutions, indeed:

```
root@d6b0018e7a61:/usr/local/tomcat/webapps/WEB-INF/lib# unzip -t print-lib-geosolutions-2.0-20190412.084441-4.jar 
Archive:  print-lib-geosolutions-2.0-20190412.084441-4.jar
[...]
    testing: org/mapfish/             OK
    testing: org/mapfish/print/       OK
    testing: org/mapfish/print/config/   OK
    testing: org/mapfish/print/config/layout/   OK
    testing: org/mapfish/print/legend/   OK
    testing: org/mapfish/print/map/   OK
    testing: org/mapfish/print/map/readers/   OK
    testing: org/mapfish/print/map/readers/google/   OK
    testing: org/mapfish/print/map/renderers/   OK
    testing: org/mapfish/print/map/renderers/vector/   OK
    testing: org/mapfish/print/output/   OK
    testing: org/mapfish/print/scalebar/   OK
    testing: org/mapfish/print/servlet/   OK
    testing: org/mapfish/print/utils/   OK
[...]
```

About the issue with the redirections, it seems that the connector is not configured in tomcat, so it might need a customization once installed in the Rennes-Métropole environment.

also, I see in the previous messages that mapstore is making use of its own (XHR ?) proxy ?

```
https://portail-test.sig.rennesmetropole.fr/mapstore/proxy/?url=https%3A%2F%2Fportail-test.sig.rennesmetropole.fr%2Fcas%2Flogin%3Fservice%3Dhttps%253A%252F%252Fportail-test.sig.rennesmetropole.fr%252Flogin%252Fcas
```

I don't know if this is customizable, so that we can use the one from the SP instead ? (`"/proxy/?url=..."`)

**Comment by landryb** [comment]
> also, I see in the previous messages that mapstore is making use of its own (XHR ?) proxy ?
> I don't know if this is customizable, so that we can use the one from the SP instead ? (`"/proxy/?url=..."`)

+1, i think this was already brought up by @fvanderbiest at some point

**Comment by offtherailz** [comment]
> Is the back printing module included in the docker image latest here ?
Yes, I confirm what @pmauduit said. the printing module already is included in geOrchestra's MapStore, as a custom jar inside it.

About the redirection, I don't know the exact configuration of every setup, but in order to avoid confusion I suggest to find a solution that doesn't require any manual configuration.
If the print module is used only by MapStore, maybe setting the env variable `PRINT_BASE_URL="/mapstore/pdf/info.json"` in the docker image of should solve the problem in every installation without any configuration. What do you think about it?

About the proxy: MapStore has its own, embedded. We always used it in the tests, and the documentation tells how to configure it. So I shouldn't replace it for the moment.

Anyway using the geOrchestra's one doesn't look to be a problem. I tried it a little bit and it seems to work well with MapStore.
So for a future release we can start using it and removing the MapStore's internal one in favour of this.

**Comment by offtherailz** [comment]
I added this changes to our fork of georchestra-docker and it works. Probably this could solve all the problems of printing.
https://github.com/geosolutions-it/georchestra-docker/pull/1/files
