### ISSUE TITLE
Plugin Identify Properties

### ISSUE THREAD

**Issue by catmorales** [georchestra/mapstore2-georchestra#288]
Hello,
I need to create a customized info sheet for an application context.
I need to generalize in this context for all layers of the map,  the display of the info page:
* in "properties" format
* without the tools present here :

![image](https://user-images.githubusercontent.com/4659829/96715232-911b1400-13a3-11eb-99ae-8cc7c240170a.png)

I tried to set it up in the configuration of the "Identify" plugin but I can't do it.
**Can you tell me how to do it?** 

 I read  the doc [here](https://mapstore.geo-solutions.it/mapstore/docs/api/plugins#plugins.Identify) but i don't see nothing about how to disabble the tools. 
I tried to add the "mapinfo" options but when saving the application context these elements are not saved.
My current configuration : 

![image](https://user-images.githubusercontent.com/4659829/96715967-afcdda80-13a4-11eb-846f-b693981af320.png)

```

**Comment by tdipisa** [comment]
@catmorales

> in "properties" format

Currently, this is possible only as a general setting in localConfig, so it cannot be configured at context level. We have anyway an issue for this [here](https://github.com/geosolutions-it/MapStore2/issues/5504) for which there is a [pending PR](https://github.com/geosolutions-it/MapStore2/pull/5578) still in pending review. I'm not sure that we will be able to include this in the next major release since more work is needed.

In context wizard step 2 (map configuration), you can anyway configure the identify format layer by layer in the TOC->LayerSettings 

> without the tools present here :

It is possible but I've just realized that the plugin online documentation is not updated for this. The JS doc is present anyway, we are checking it now. Below are the configuration properties you have to use:

```
    "showMoreInfo": false,
    "enabledCoordEditorButton": false,
```

![2020_11_24_10_27_04_MapStore_HomePage](https://user-images.githubusercontent.com/1280027/100075041-bd60ff00-2e3f-11eb-9441-30f7f25af185.png)
