### ISSUE TITLE
GetFeatureInfo still active while using another tool ?

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/mapstore2-georchestra#408]
See below. Same effect if you close the Urbanisme plugin too before using the measurement tool.

![ms2_urbanisme_GFI_still](https://user-images.githubusercontent.com/6370443/126281386-20fc5474-0240-4819-a453-66f0ff51e2ab.gif)

And same thing without using anything before and in our default context.

![ms2_urbanisme_GFI_still3](https://user-images.githubusercontent.com/6370443/126283116-02276086-034d-4343-a417-0673c6c1092d.gif)

Anyone to reproduce that ?
@landryb @juliensabatier ?

**Comment by tdipisa** [comment]
@MaelREBOUX 
I think it is related to the same problem reported [here in #134](https://github.com/georchestra/mapstore2-cadastrapp/issues/134#issuecomment-883387890).

The problem is present in your portail-test (tested [here](https://portail-test.sig.rennesmetropole.fr/mapstore/#/context/master-urba-foncier)) but not in portail.sig (tested [here](https://portail.sig.rennesmetropole.fr/mapstore/#/context/master-urba-foncier)).

**Comment by MaelREBOUX** [comment]
I confirm that. Sorry for the noise...
