### ISSUE TITLE
Finalize MOM MS3 - Phase I

### ISSUE THREAD

**Issue by offtherailz** [georchestra/mapstore2-georchestra#425]
At the end of development for issues of [MOM MS3](https://github.com/georchestra/mapstore2-georchestra/milestone/10), create a new stable branch for mapstore2-georchestra (1.3.x) and tag the version 1.3.0.

**Comment by landryb** [comment]
as far as i'm concerned, https://github.com/georchestra/mapstore2-georchestra/issues/422#issuecomment-972767996 is what should be done, branch `20.1.x`.

**Comment by tdipisa** [comment]
> as far as i'm concerned, [#422 (comment)](https://github.com/georchestra/mapstore2-georchestra/issues/422#issuecomment-972767996) is what should be done, branch `20.1.x`.

I suppose to, we just need a confirmation from the georchestra team.

**Comment by catmorales** [comment]
@pmauduit , @fvanderbiest  could you confirm the Landry's proposition ?

**Comment by fvanderbiest** [comment]
Jumping in, sorry I'm late to the game.

`20.1.x` is the latest stable branch from 2020.
There was no major release last year (2021) but a `22.0.0` release is planned this month if everything goes well.

Should MapStore-georchestra be tagged as geOrchestra itself ? 
That's a good question.

IIUC, this MS3 contract's main purpose was to upgrade to MapStore 2021.02.xx which is mapstore's latest stable release and provides new features compared to the older one we had in geOrchestra.
If we stick to geOrchestra habits, this should not happen on the `20.1.x` branch (which is only meant for bugfixes on `20.1.0`).
Instead this should be part of the next major release (`22.0.0`).

The reason why I'm questioning the same-tag-as-georchestra motto is that we probably do not want to delay a mapstore-georchestra release because we're late releasing geOrchestra 22. Also, it probably makes sense to keep the tags aligned with upstream mapstore, to keep it simple-to-follow.

Other opinions welcome here.

**Comment by landryb** [comment]
agreed on "not delaying", but iirc ppl wanted to have a consistent set of things be a part of a georchestra release, eg tagging the ms2-geor repo when the geor repo was tagged for a release.. really, i don't care if the branch name is  2021.02.xx or 22.0.x or 1.3.x, it's **just** a branch name :) please someone pick something and stick to it :D

**Comment by catmorales** [comment]
Hello  @tdipisa , @offtherailz 
To answer this question and to finish on this point, we finally decided to align ourselves with the versions of mapstore2 so this one would be 2021.02.xx.

**Comment by tdipisa** [comment]
@catmorales ok we will proceed with this, the new stable branch of ms2-gs will be 2021.02.xx. Independent tags for project minor releases can be done starting from this when needed according to the ms2-gs release schedule.

**Comment by tdipisa** [comment]
@catmorales since we have already merged #436 on master, we will proceed to create the new stable branch after functional our tests in DEV instance.

**Comment by catmorales** [comment]
@tdipisa I'd like to test the last improvements in pedestrian view but i need this new stable branch in[ your docker images repository](https://hub.docker.com/r/geosolutionsit/mapstore2-georchestra/tags) to do it. I wanted to test it before sending you the VA document for this phase. Will it be possible to have it today ? Otherwise, i'll put a reserve on it

**Comment by tdipisa** [comment]
@catmorales [branch created](https://github.com/georchestra/mapstore2-georchestra/tree/2021.02.xx) and image available in [docker hub](https://hub.docker.com/layers/geosolutionsit/mapstore2-georchestra/2021.02.xx/images/sha256-a4335c146441b8ff1a0c53de75dda444d0b7cbf4cc4dc64ef3225a8bf509a785?context=explore)

**Comment by fvanderbiest** [comment]
From a "geOrchestra project" point of view, it would also make sense to have an image tagged in https://hub.docker.com/r/georchestra/mapstore IIUC
