### ISSUE TITLE
Feature Attribute Form - Identify tool - Edit mode

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#45]
The Identify tools (#44) can switch in edit mode to:

- Allow the user to edit the object attributes 
- Allow the user to edit the corresponding object geometry on map

An edit button can be enabled by the administrator for the Identify tool (with a specific configuration property) in order to automatically open the [Attribute Table](https://mapstore.readthedocs.io/en/latest/user-guide/attributes-table/):

1. According to the Identify output format, an edit button can be provided for each retrieved feature in the Identify response (eg. the JSON output format) instead of having a generic edit button (eg. HTML or Text format) 
2. The Attribute Table opens **in edit mode** by clicking on the edit button and a record inside the table (the layer's feature) will be automatically selected if possible (depending on the output format, see point 1) 
3. Once the Attribute Table opens the Identify tool can close

Related issue in MapStore : https://github.com/geosolutions-it/MapStore2/issues/5185

**Comment by tdipisa** [comment]
@offtherailz @vlt1 
we need a simple mockup for this before staring the development, few buttons are needed here but I would like a mockup anyway.

**Comment by vlt1** [comment]
@offtherailz it seems that identify plugin works by doing WMS GetFeatureInfo request, whereas Attribute Table works through WFS. The question is how to connect two together for the purposes of editing features(in case of JSON output). I can see that WMS request contains BBOX that I'm guessing it uses to filter out the features. It looks like WFS can filter by BBOX. Can I use the BBOX from WFS request and supply it to Attribute Table filter object, then wait for the response and select the requested feature to edit from the list? Would that work? Are there other ways to do it? What do you think? Also it looks like the floating identify tool is not ready yet(there is a pending pr for it). Should it be ignored for now?

**Comment by offtherailz** [comment]
**Some clarifications**
- Only the layers that can can open attribute table can have the edit link in feature info (so the search --> type: wfs entry). This means that WMS service have a corresponding WFS service layer with the same name do browse vector data
- The pending PR should be merged in 1/2 days, so you can add the button also from that entry point. 
- WFS as various ways of filtering. bbox is not suggested because it is mutually esclusive with other kind of filtering (Filter/CQL_FILTER). 

I suggest, when the user clicks on edit button: 
-  to open the attribute table
- switch to edit mode
- filtered by point clicked using the current filtering system with a geometric intersection with the point clicked
   - note: I suggest to use the QUERY:UPDATE_FILTER, the same action used by quick filter entries. This quick filters should be automatically reset on exit from feature grid. I'm not sure it is supports also for geometric attributes, but we can add support to it.

This should filter the feature info (and also the map, if the map sync is enabled) with the original selection.
At the end you can close again the feature grid (and reset the filter)

It could be useful if this quick point intersection filter is somehow highlighted in the feature grid. 
Here I ask to @tdipisa  : 
It should be great if the quick filter is used also in normal context. Please let me know
![image](https://user-images.githubusercontent.com/1279510/79449435-7f674700-7fe3-11ea-8faf-18880495f524.png)

**Comment by vlt1** [comment]
> I'm not sure it is supports also for geometric attributes, but we can add support to it.

UPDATE_FILTER works with filterFields. If I understand correctly for geometric filtering there is a spatialField prop in filter object that is handled separately.

> filtered by point clicked using the current filtering system with a geometric intersection with the point clicked

Identify gets all features within a specific region(I assume it's the bbox), so just geometric intersection with the point clicked would not suffice, as the result would differ from Identify and we won't be able to select the needed feature. Maybe we could just use a polygon with bbox coordinates intersection, it seems like the results that we would get would be a superset of what Identify gets, so we could select the needed feature. Am I correct in this assumption?

Also there is a [pending pr](https://github.com/geosolutions-it/MapStore2/pull/5141) for an ability to select features by clicking on a map when in edit mode of Attribute Table. It modifies the edit mode flow and utilizes filters. The implementation provided there may be not to your satisfaction and should be changed. The point I'm making is that changes to filtering probably should be first introduced in that pr first. In any case I think it should be merged before we proceed with this one. With that being said please review it as soon as possible.

**Comment by tdipisa** [comment]
@offtherailz I agree with you, but please consider also the implementationof #48 that has some point of contact regaring the point selection.

**Comment by tdipisa** [comment]
@vlt1 Moving it back to ready.

If I open the Attribute table from TOC with the Identify panel opened, the marker remains in the map.
