### ISSUE TITLE
Locate Tool - Locate User 

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#53]
The Locate extension allows to localize the user in relation to its position (IP address, GPS etc). For this extension are mandatory:

- A button that allows to activate/deactivate the Locate extension
- A soon as the Locate extension is active, the map is automatically centered on the retrieved user position (the position will be refreshed every n seconds as long as the extension is active)

**Comment by gitcontributor** [comment]
@tdipisa as far as I can see, the Locate tool already included: https://georchestra.geo-solutions.it/mapstore/#/
![image](https://user-images.githubusercontent.com/61145641/75673804-d2d04080-5c94-11ea-9b4a-06fbe3995dcd.png)

**Comment by offtherailz** [comment]
The "follow user" functionality is already supported.

Actually it works this way: 
 - When you click the locate tool enables in "Follow mode" and centers the map on the user position. 
 - The map follows the user until the user interacts with the map
 - when the user move the map (zoom or pan) the follow mode deactivates and the locate tool is still active, only showing the user's position on the map. 
 - Clicking again on the locate tool will activate again the follow mode. 
 - A click on the locate tool when "follow mode" is active deactivates the tool at all, removing the user position from the map and stopping following him.

This works more or less like google maps app navigation (activate and follow until map move, then reset button to re-start following).

This should be more clear: 
- The button now looks de-activated when follow mode is deactivated. It should be green all the time. 
- when the "follow mode" is not active, the tool should tell "follow my position" and when is active it should show "stop showing my position" (because a second click deactivates the tool at all).

Please @gitcontributor do the following: 
 - Verify that the following functionality still works as explained (with some position change simulator, there should be some chrome extension or something similar)
 - Implement the improvement to button above
 - Document better this functionality

**Comment by ElenaGallo** [comment]
When the follow mode and the user position are deactivated, the  locate button it doesn't have to be green.
