### ISSUE TITLE
Import/export of WMC

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#60]
- Within a map context the user must be able to import a map in WMC format (see #5 for WMC samples). The import will replace the current map state with the imported one. The MS's [Import tool](https://mapstore.readthedocs.io/en/latest/user-guide/import/) need to be improved to accomplish this task. 

- Within a map viewer the user must be able to export the current map in WMC format (see #5 for WMC samples). The [Export tool](https://mapstore.readthedocs.io/en/latest/user-guide/menu-bar/#burger-menu) present in Burger Menu that is currently available in MS needs to be improved to export the current map context in a different format than the native JSON as it is now.

![export_improved](https://user-images.githubusercontent.com/1280027/74040782-b528f780-49c4-11ea-9152-8ba1c40ef945.jpg)

Conversion procedures could be implemented between the standard MS's format and the above required ones.

**Proper icons for the format items inside the menu need to be built**

**Comment by offtherailz** [comment]
### Mapping custom parts

**About layers types:** 

We are missing WMTS and TMS implementations (in mapstore we have TMS backgrounds and WMTS catalog where to add layers). **These are totally missing in the standard** (See Future work [here](file:///home/nali/Downloads/05-005_Web_Map_Context_Documents_Implementation_Specification.pdf) I suggest in this case is to completely skip these layers during export. (Exporting not compliant XML may cause incompatibility and so issues in interoperability. 

@tdipisa these limitation need to be explicitly expressed by the UI (discouraging for export in WMC context. I also suggest to disable export in this format, because of the limitations

**About WMS Layers:** 

The mainly missing entries are: 
 - Layer Groups 
 - `search` (WFS URL entry) 
Future : 
 - Filters
 - Dimension (time,elevation)


As expressed before, I suggest to provide only a minimal support in export/import for this format.
Therefore I suggest to provide only link to WFS service and layer groups, as exension of the layer. 

#### General 
Here a sample of a WMS layer JSON representation. 
Example: 

```javascript
{
    id: 'topp:states__6', 
    format: 'image/png8', <-- imageFormat (extension)
    search: { <-- WFS LINK (extension, to create)
      url: 'https://demo.geo-solutions.it:443/geoserver/wfs',
      type: 'wfs'
    },
    name: 'topp:states',
    opacity: 1, (extension)
    description: 'This is some census data on the states.',
    title: 'USA Population',
    type: 'wms',
    url: 'https://demo.geo-solutions.it:443/geoserver/wms',
    bbox: { //<-- maxExtent and/or BoundingBox
      crs: 'EPSG:4326',
      bounds: {
        minx: -124.73142200000001,
        miny: 24.955967,
        maxx: -66.969849,
        maxy: 49.371735
      }
    },
    visibility: true,
    singleTile: false, <-- extension: singleTile (extension)
    dimensions: [], 
    queriable: false, <-- queriable (extension) 
    
  }
```

#### Search (WFS)
MapStore map contains this entry that allows link to attribute table: 

```javascript
search: {
      url: 'https://gs-stable.geo-solutions.it/geoserver/wfs',
      type: 'wfs'
    },
``` 

This can be mapped as an extension easely with the proper tag. 

#### Layer groups 
`group` entry links to the id of the group in groups entry. Here you need to create an extension to map this. 
@tdipisa @vlt1 if too complicated, we can add everything to default group. 

### Dimension 

** i report this to give complete information, but I don't suggest to export this ** 

And **dimensions** can be these 2 kinds of objects:
```javascript
dimensions: [
    {
      source: {
        type: 'multidim-extension',
        url: 'https://gs-stable.geo-solutions.it/geoserver/gwc/service/wmts'
      },
      name: 'time'
    }
  ]
```
or
```javascript
dimensions: [{
        name: 'elevation',
        units: 'meters',
        unitSymbol: 'm',
        'default': '0.0',
        values: [
          '0.0',
          '200.0',
          '400.0',
          '600.0',
          '800.0',
          '1000.0',
          '1200.0',
          '1400.0',
          '1600.0',
          '1800.0',
          '2000.0',
          '3000.0',
          '4000.0',
          '5000.0',
          '6000.0',
          '7000.0',
          '8000.0',
          '9000.0'
        ]
      },
      {
        name: 'REFERENCE_TIME',
        units: 'ISO8601',
        unitSymbol: 't',
        'default': '2016-02-25T00:00:00.000Z',
        values: [
          '2016-02-23T00:00:00.000Z',
          '2016-02-24T00:00:00.000Z',
          '2016-02-25T00:00:00.000Z'
        ]
      }]
```

**Comment by tdipisa** [comment]
@allyoucanmap can you please provide two new icons for this implementation?

**Comment by tdipisa** [comment]
@vlt1 as I mentioned during the weekly meeting, please remember that with the support that you are developing within this issue we need to provide the ability to load a WMC template in the map (#151).

**Comment by allyoucanmap** [comment]
@tdipisa 
JSON icon is already available, below the WMC one.
![image](https://user-images.githubusercontent.com/19175505/74816941-65b7c500-52fc-11ea-8eda-198b47a2868e.png)

**Comment by tdipisa** [comment]
@allyoucanmap thank you so much.
