### ISSUE TITLE
Problem printing when not connected

### ISSUE THREAD

**Issue by jusabatier** [georchestra/mapstore2-georchestra#650]
**Describe the bug**
When not connected, after loading a public context, if I zoom in and then try to use the print function, the preview still blank.
Trying to generate the PDF also result in a blank map.

If I try printing without zooming in, it works.

**To Reproduce**
1. Go to ['a public context'](https://geoportail.lepuyenvelay.fr/mapstore/#/context/Public)
2. Zoom in
3. Use the print function
4. See error : preview is blank
5. Trying to print result in a PDF with blank map

**Expected behavior**
Preview should display the current map state and printing should generate a PDF with current map.

**Screenshots**
![image](https://github.com/georchestra/mapstore2-georchestra/assets/8310116/ac981cb1-a261-4965-adef-a6f553ccef33)

**Additional context**
Versions : 
MapStore2-geOrchestra	:2023.02.00-RC2-geOrchestra(69690b0e)
MapStore2	:2023.02.xx(c4f94e3b)

**Comment by landryb** [comment]
using this version:

MapStore2-geOrchestra	:[2023.02.xx](https://github.com/georchestra/mapstore2-georchestra/commits/2023.02.xx)[(76035d4f)](https://github.com/georchestra/mapstore2-georchestra/commit/76035d4f5d1aab708964f233e0236efc093be7c2)
MapStore2	:[2023.02.xx](https://github.com/geosolutions-it/MapStore2/commits/2023.02.xx)[(6a5d2de3)](https://github.com/geosolutions-it/MapStore2/commit/6a5d2de3011a47bef2905fbfb19d489e89f700d8)

created an empty context, added print zoom in zoom out, made the context public, i have a different issue but that might be a misconfiguration on my side (apache headers, https vs http, etc..), because printing tries to go through the ms2 proxy and that doesn't make sense.

https://georchestra.dev.craig.fr/mapstore/proxy/?url=http://georchestra.dev.craig.fr/mapstore/pdf/create.json

i can reproduce the issue on our context/instance on https://geoportail.lepuyenvelay.fr/mapstore/#/context/Public

**Comment by jusabatier** [comment]
Related with https://github.com/geosolutions-it/MapStore2/issues/9346
and fixed in RC3
