### ISSUE TITLE
Project update to the latest MapStore 2024.02

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#714]
## Description

It is requested to update the project to the latest MapStore version. The MapStore revision need to be updated to the latest stable branch **[2024.02.xx](https://github.com/geosolutions-it/MapStore2/tree/2024.02.xx)**.

### Checks

It is necessary to check if the existing customizations are properly working after the project update. Custom specific extensions that are involved as part of this update work are the following. These will be tested separately for:

- [ ] https://github.com/georchestra/mapstore2-cadastrapp
- [ ] https://github.com/sigrennesmetropole/geor_urbanisme_mapstore

### Notes

The project need to be updated by following the official [migration guidelines](https://mapstore.readthedocs.io/en/latest/developer-guide/mapstore-migration-guide/) involved.

In particular in the **master** branch

- [x] update version in package.json to be aligned to the new release version
- [x] update version present in version.txt accordingly

Preliminary checks and tests for this update will be performed on https://georchestra.geo-solutions.it/

Release procedures to follow are reported in [project README](https://github.com/georchestra/mapstore2-georchestra?tab=readme-ov-file#release-procedure).

**Comment by ElenaGallo** [comment]
@tdipisa tests done, they are available [here](https://studio.cucumber.io/projects/292756/test-runs/1014773/overview) and [here](https://studio.cucumber.io/projects/150902/test-runs/1014779/folder-snapshots/11909396)

**Comment by tdipisa** [comment]
@dsuren1 From functional tests performed it seems you have missed to add/consider the following in default config:

- IFC source
- ArcGIS source
- config.yaml updates according to:
   - https://docs.mapstore.geosolutionsgroup.com/en/v2024.01.02/developer-guide/mapstore-migration-guide/#print-config-file-update
   - https://docs.mapstore.geosolutionsgroup.com/en/v2024.01.02/developer-guide/mapstore-migration-guide/#enable-showing-creditsattribution-text-in-print-config

Can you please raise a PR to provide what is missing? Thank you so much.

**Comment by landryb** [comment]
to the ones trying the upgrade path to 2024.02, some notes:
- first i had error messages from hibernate telling me that the georchestra db user wasnt the owner of the tables in the `mapstore` schema, i fixed those:
```
[[local]:5432] postgres@georchestra=# alter SCHEMA mapstore owner to georchestra ;
[[local]:5432] postgres@georchestra=# alter table mapstore.gs_attribute owner to georchestra ;
[[local]:5432] postgres@georchestra=# alter table mapstore.gs_category owner to georchestra ;
[[local]:5432] postgres@georchestra=# alter table mapstore.gs_resource owner to georchestra ;
[[local]:5432] postgres@georchestra=# alter table mapstore.gs_security owner to georchestra ;
[[local]:5432] postgres@georchestra=# alter table mapstore.gs_stored_data owner to georchestra ;
[[local]:5432] postgres@georchestra=# alter table mapstore.gs_user owner to georchestra ;
[[local]:5432] postgres@georchestra=# alter table mapstore.gs_user_attribute owner to georchestra ;
[[local]:5432] postgres@georchestra=# alter table mapstore.gs_user_group_attribute owner to georchestra ;
[[local]:5432] postgres@georchestra=# alter table mapstore.gs_usergroup owner to georchestra ;
[[local]:5432] postgres@georchestra=# alter table mapstore.gs_usergroup_members owner to georchestra ;
```
- next, hibernate didnt apply the DDL to upgrade the schema because of this default setting (cf https://github.com/georchestra/datadir/blob/master/mapstore/geostore-datasource-ovr.properties#L7):
```
geostoreEntityManagerFactory.jpaPropertyMap[hibernate.hbm2ddl.auto]=validate
```
- so and accessing `/mapstore/rest/geostore/extjs/search/category/MAP/***/thumbnail,details,featured` triggered tracebacks in the log:
```
SqlExceptionHelper.logExceptions() - ERROR: column resource0_.advertised does not exist
```

so i followed https://docs.mapstore.geosolutionsgroup.com/en/latest/developer-guide/mapstore-migration-guide/#database-update, but had to manually adapt some bits
```
:/tmp $wget https://github.com/geosolutions-it/geostore/raw/refs/heads/master/doc/sql/migration/postgresql/postgresql-migration-from-v.2.0.0-to-v2.1.0.sql
:/tmp $sed -i -e 's/gs_resource/mapstore.gs_resource/' postgresql-migration-from-v.2.0.0-to-v2.1.0.sql
:/tmp $sed -i -e 's/geostore/mapstore/g' postgresql-migration-from-v.2.0.0-to-v2.1.0.sql
[localhost:5432] georchestra@georchestra=> \i /tmp/postgresql-migration-from-v.2.0.0-to-v2.1.0.sql
ALTER TABLE
Time: 29.472 ms
ALTER TABLE
Time: 0.681 ms
ALTER TABLE
Time: 11.099 ms
UPDATE 0
Time: 57.612 ms
```

with that done the db schema is updated, requests to the backend now succeed, and i see maps in the map loader/on `/mapstore/#/home`, and existing contexts on `/mapstore/#/admin`.

maybe `geostoreEntityManagerFactory.jpaPropertyMap[hibernate.hbm2ddl.auto]` should be set to `update` to ease upgrades ?
